# Generated by Django 4.2.6 on 2023-12-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(default=None, unique=True, verbose_name='ID телеграме'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_name',
            field=models.CharField(default=123, max_length=100, verbose_name='Ник в телеграме'),
            preserve_default=False,
        ),
    ]
