# Generated by Django 4.2.8 on 2023-12-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prize.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('House', 'Дома'), ('Job', 'На работе'), ('Street', 'На улице'), ('Other', 'Другое')], max_length=10, verbose_name='Место')),
                ('time', models.CharField(choices=[('Morning', 'Утром'), ('Day', 'Днём'), ('Evening', 'Вечером'), ('Night', 'Ночью')], max_length=10, verbose_name='Время')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('good_habit', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('period', models.CharField(choices=[('1', 'Раз в неделю'), ('2', 'Два раза в неделю'), ('3', 'Три раза в неделю'), ('4', 'Четыре раза в неделю'), ('5', 'Пять раз в неделю'), ('6', 'Шесть раз в неделю'), ('7', 'Семь раз в неделю')], max_length=20, verbose_name='Периодичность')),
                ('prize', models.FloatField(verbose_name=prize.models.Prize)),
                ('time_to_complete', models.IntegerField(max_length=120, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('associated_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('user', 'action', 'date_of_creation'),
            },
        ),
    ]
